context: {}

package:
  name: road-dashboards

  version: ${{ env.get("PROJECT_VERSION") }}


source:
  path: ../

build:
  script: "python -m pip install --no-deps --ignore-installed -vv ."
  noarch: python



requirements:
  host:
    - python
    - pip
    - hatch

  run:
    - python
    - pydantic
    - fire
    - pyyaml
    - loguru
    - orjson
    - typing_extensions >=3.7.4
    - pycountry
    - dash-bootstrap-components
    - dash-daq
    - numpy
    - pandas
    - boto3
    - tqdm
    - fsspec
    - road-database-toolkit >= 0.1.42
    - jira
    - python-kaleido
    - scipy
    - sqlalchemy

about:
  homepage: http://gitlab.mobileye.com/road_algo/road-dashboards
  summary: "Road dashboards repository"

