pipe:
  params:
    ci_task: 'ci-flow'
    taskfile: 'tasks/ci.tasks.yml'
    notify_users: 'sys_objx@mobileye.com'
    delete_work_dir: true
  const:
    subpath: '.'
    build_type: 'conda:build'
    jenkins_artifacts_paths: >
      __build_info/**/*,
      __localbuild__/coverage/coverage_html/**/*,
      __localbuild__/pytest/**/*,
      __localbuild__/docs/**/*
    junit_artifacts_path: >
      __localbuild__/pytest/**/*_junit.xml

  #  ---- secrets configuration ----
  # vault: []

mkdocs:
  params:
    ci_task: 'ci-flow:build:mkdocs'
    taskfile: 'tasks/ci.tasks.yml'
    notify_users: 'sys_objx@mobileye.com'
    delete_work_dir: true
  const:
    subpath: '.'
    build_type: 'mkdocs:build'
    jenkins_artifacts_paths: >
      __build_info/**/*,
      __localbuild__/docs/**/*
