# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3.10

exclude: (^.pixi/)
repos:
  - repo: local
    hooks:
      - id: check-yaml
        name: Check YAML
        entry: pixi run --environment=lint check-yaml
        language: system
        types: [yaml]
      - id: check-added-large-files
        name: Check for large files
        entry: pixi run --environment=lint check-added-large-files
        language: system
      - id: end-of-file
        name: Check end-of-file
        entry: pixi run --environment=lint end-of-file-fixer
        language: system
        types: [text]
      - id: trailing-whitespace
        name: Fix trailing whitespace
        entry: pixi run --environment=lint trailing-whitespace-fixer
        language: system
        types: [text]
      - id: check-json
        name: Check JSON
        entry: pixi run --environment=lint check-json
        language: system
        types: [json]
      - id: yaml-format
        name: YAML format
        entry: pixi run --environment=lint prettier-fmt
        language: system
        types: [file, yaml]
      # TOML format
      - id: toml-format
        name: TOML format
        entry: pixi run --environment=lint toml-format
        language: system
        types: [toml]
      # Python linting with Ruff
      - id: ruff
        name: Ruff lint
        entry: pixi run --environment=lint ruff-lint
        language: system
        types_or: [python, pyi]
        require_serial: true
      - id: ruff-format
        name: Ruff format
        entry: pixi run --environment=lint ruff-format
        language: system
        types_or: [python, pyi]
        require_serial: true
