version: '3'

includes:
  docker: docker/docker.tasks.yml

vars:
  GIT_ROOT_PATH:
    sh: "realpath $(git rev-parse --show-toplevel)"

env:
  DIMAGE: artifactory.sddc.mobileye.com/me-conda-docker-local/mx-conda-py310

tasks:
  _show_variables:
    cmds: [env]

  denv:dev:
    desc: "Run the docker environment"
    cmds:
      - |
        abs_path_to_repo_root=$(realpath $(git rev-parse --show-toplevel))
        abs_path_to_subpath_dir=$(realpath .)
        rel_path_to_subpath_dir=$(realpath --relative-to="${abs_path_to_repo_root}" "${abs_path_to_subpath_dir}")
        rel_path_to_repo_root=$(realpath --relative-to="${abs_path_to_subpath_dir}" "${abs_path_to_repo_root}")

        REPO_DIR_HOST=${abs_path_to_repo_root}
        WORKDIR_REL_PATH=${rel_path_to_subpath_dir}
        WORKDIR_HOST=$(realpath ${REPO_DIR_HOST}/${WORKDIR_REL_PATH})
        echo -e "[mx-tools:denv] @@SCRIPT_DIR=${SCRIPT_DIR} REPO_DIR_HOST=${REPO_DIR_HOST}"
        echo -e "[mx-tools:denv] @@WORKDIR_REL_PATH=${WORKDIR_REL_PATH} WORKDIR_HOST=${WORKDIR_HOST}"

        REPO_NAME=$(basename $(readlink -f $REPO_DIR_HOST))
        REPO_DIR_GUEST=/repos/$(basename ${REPO_DIR_HOST})
        WORKDIR_GUEST=${REPO_DIR_GUEST}/${WORKDIR_REL_PATH}
        echo -e "[mx-tools:denv] REPO_NAME=${REPO_NAME} REPO_DIR_GUEST=${REPO_DIR_GUEST} WORKDIR_GUEST=${WORKDIR_GUEST}"
        docker run --rm -it --privileged -p 4000:8000 --workdir ${REPO_DIR_GUEST} -v ${REPO_DIR_HOST}:${REPO_DIR_GUEST} -v ${HOME}/.de:/home/me.docker/.de -v /dev/fuse:/dev/fuse -v ${HOME}/tmp/.aws/:/home/me.docker/.aws/ ${DIMAGE} 
