# https://taskfile.dev

Description: >
  This tasker lib encapsulates dev only tasks.
  Tasks here usually just run a few infra libs tasks.

version: "3"

tasks:

  check:
    desc: check code
    cmds:
      - pylint .

  get-started:
    desc: create dev env, install pkg in dev to get started
    vars:
      META_DEV_ENV_NAME:
        sh: "yq4 .META_DEV_ENV_NAME {{.CONDA_LIB_CONFIG_YML}}"
    cmds:
      - task conda:venv:update:dev-env
      - mamba run --no-capture-output -n {{.META_DEV_ENV_NAME}} task dev:install-dev-mode
      - |
        echo "
        Hi $(whoami),

        please run:

          conda activate {{.META_DEV_ENV_NAME}}

        and get started.
        "
    silent: true

  conda:package:build:
    desc: build your conda package locally
    cmds:
      - task ci:init-clean-flow:local
      - task conda:package:build
      - task conda:build:show:local-build-contents
    silent: true

  conda:package:full-build:
    desc: build, install and test your conda package locally
    vars:
      LOCAL_CONDA_BUILD_DIR:
        sh: "yq4 .LOCAL_CONDA_BUILD_DIR {{.CONDA_LIB_CONFIG_YML}}"
    cmds:
      - task ci:init-clean-flow:local
      - task conda:package:full-build
    silent: true

  install-dev-mode:
    desc: Install package in dev-mode in current active env
    cmds:
      - task ci:init-clean-flow:local
      - task conda:package:install:dev-mod
    silent: true