# Use an official Python runtime as a parent image
FROM ghcr.io/prefix-dev/pixi:latest AS build
USER root
# Set the working directory to /app
WORKDIR /app/road_dashboards/workflows_dashboard

# Copy the current directory contents into the container at /app
COPY ./road_dashboards/workflows_dashboard /app/road_dashboards/workflows_dashboard

RUN chmod 777 -R /app
RUN pixi init --import env.yaml
RUN pixi install

RUN pixi shell-hook -e default -s bash > /shell-hook
RUN echo "#!/bin/bash" > ./entrypoint.sh
RUN cat /shell-hook >> ./entrypoint.sh
# extend the shell-hook script to run the command passed to the container
RUN echo 'exec "$@"' >> ./entrypoint.sh


FROM python:3.12-slim
WORKDIR /app/road_dashboards/workflows_dashboard
COPY --from=build /app/road_dashboards/workflows_dashboard/.pixi/envs/default /app/road_dashboards/workflows_dashboard/.pixi/envs/default
COPY --from=build --chmod=0755 /app/road_dashboards/workflows_dashboard/entrypoint.sh /app/road_dashboards/workflows_dashboard/entrypoint.sh
# copy your project code into the container as well
COPY ./road_dashboards/workflows_dashboard /app/road_dashboards/workflows_dashboard

ENV PYTHONPATH=/app
ENV AWS_STS_REGIONAL_ENDPOINTS=regional
ENV DEBUG=false


# Make port 6009 available to the world outside this container
EXPOSE 6009

# set the entrypoint to the shell-hook script (activate the environment and run the command)
ENTRYPOINT ["/app/road_dashboards/workflows_dashboard/entrypoint.sh"]

# Run app.py when the container launches
CMD ["python", "app.py"]
