version: "3"

vars:
  GREETING: Clean Tasks

tasks:
  pyc:
    desc: _
    cmds:
      - sh -c "find . -name '*.pyc' -delete"

  pycache:
    desc: _
    cmds:
      - sh -c "find . -type d -name '__pycache__' -exec rm -rf {} +"

  pytest:
    desc: _
    cmds:
      - sh -c "find . -type d -name '.pytest_cache' -exec rm -rf {} +"
      - sh -c "find . -type f -name '.coverage*' -exec rm -rf {} +"

  py-all:
    desc: _
    deps:
      - pyc
      - pycache
      - pytest
    cmds:
      - echo "@@[kind=cleanup status=cleanup.finished]@@"

  git-safe:
    desc: _
    cmds:
      - git clean -dxf -e .vscode/
