# https://taskfile.dev

version: "3"

tasks:
  fmt:
    desc: run code auto format
    cmds:
      - black . --line-length 120 .

  check:
    desc: check code
    cmds:
      - pylint .

  check-black:
    desc: check code with black formatter
    cmds:
      - black --check --line-length 120 .

  jupyter:
    desc: run jupyter server
    cmds:
      - jupyter-lab --no-browser --ip='*' --NotebookApp.token='' --NotebookApp.password=''

  _remove:
    desc: remove patterns
    cmds:
      - find . -path './.*' -prune -o -name '{{.pattern}}' -type {{.type}}  -print | xargs -n 1 -P4 rm -rf
    prefix: "{{._remove}}:{{.pattern}}"

  clean:
    desc: clean python files
    deps:
      - task: _remove
        vars: { remove: "*.pyc", type: f }
      - task: _remove
        vars: { remove: "*.pyo", type: f }
      - task: _remove
        vars: { remove: ".pytest_cache", type: d }
      - task: _remove
        vars: { remove: ".__pycache__", type: d }
    cmds:
      - |
        echo "[denv] @@[.level=info \
        .vars=@[.action=done.{{.TASK}} .status=success]@ \
        .msg='@{.action} to @{.target} with docker image @{.dimage}' ]@@"
