# https://taskfile.dev

version: "3"

vars:
  PACKAGE_VENV_BASE:
    sh: "yq4 .PACKAGE_VENV_BASE {{.CONDA_LIB_CONFIG_YML}}"
  VENV_NAME_PYINSTALLER: "{{.PACKAGE_VENV_BASE}}-pyinst"
  VENV_RUN: "mamba run -n {{.VENV_NAME_PYINSTALLER}}"
  PACKAGE_META_YAML_PATH:
    sh: "yq4 .PACKAGE_META_YAML_PATH {{.CONDA_LIB_CONFIG_YML}}"

tasks:
  venv:remove:
    desc: _
    cmds:
      - mamba env remove -n {{.VENV_NAME_PYINSTALLER}} || echo "Already removed {{.VENV_NAME_PYINSTALLER}}"

  venv:ensure:
    desc: _
    cmds:
      - mamba create -n {{.VENV_NAME_PYINSTALLER}} -y python=3.7.7 pip
    status:
      - |
        {{.VENV_RUN}} which python | grep python

  venv:update:
    desc: update virtual environment
    deps:
      - venv:ensure
    vars:
      DEPS_RUN:
        sh: yq4 -o=json .requirements.run {{.PACKAGE_META_YAML_PATH}} | jq '.[]' | tr '\n' ' '
      DEPS_BUILD:
        sh: yq4 -o=json .requirements.mx_build_deps {{.PACKAGE_META_YAML_PATH}} | jq '.[]' | tr '\n' ' '
    cmds:
      - mamba install -y -n {{.VENV_NAME_PYINSTALLER}} {{.DEPS_BUILD}} {{.DEPS_RUN}}
      - mamba install -n {{.VENV_NAME_PYINSTALLER}} -y pip
      - mamba install -n {{.VENV_NAME_PYINSTALLER}} -y Pyinstaller
    prefix: "{{.TASK}}:{{.VENV_NAME_PYINSTALLER}}"

  build:
    desc: Demo of build with pyinstaller2
    cmds:
      - mkdir -p __localbuild__/pyinstaller
      - |
        {{.VENV_RUN}} {{.MXPACK_EXE}} pyinstaller-build info-dump
      - |
        bash --login -c '
        conda activate  {{.VENV_NAME_PYINSTALLER}};
          pyinstaller mxp.spec \
            --log-level=INFO \
            --onefile \
            --distpath $(yq4 .distpath __build_info/mxpack/pyinstaller__pre_build__info.json) \
            --workpath $(yq4 .workpath __build_info/mxpack/pyinstaller__pre_build__info.json)
        '
      - |
        {{.VENV_RUN}} {{.MXPACK_EXE}} pyinstaller-build post-dump

  clean:
    desc: clean pyinstaller build artifacts
    cmds:
      - rm -rf __localbuild__/pyinstaller

  rebuild:
    desc: full build cycle
    deps:
    cmds:
      - task pyinstaller:clean
      - task pyinstaller:venv:update
      - task pyinstaller:build
