version: "3"

vars:
  GREETING: Version

tasks:
  show:
    desc: _
    cmds: ["{{.MXPACK_EXE}} version-info info-infer dict"]
    silent: true
    prefix: "-"

  info:prebuild:write:
    desc: _
    cmds:
      - "{{.MXPACK_EXE}} frozen_build_dump"
      - "{{.MXPACK_EXE}} conda-build info-dump"

  bump:
    desc: _
    cmds: ["{{.MXPACK_EXE}} version-ctl bump"]

  commit-bump:
    desc: _
    cmds: ["{{.MXPACK_EXE}} version-ctl commit-bump"]

  push-bump:
    desc: commit bumped files
    cmds: ["{{.MXPACK_EXE}} version-ctl push-bump"]
