version_schema: "0.0.1"

project_info:
  info_path: "mxpack/project_info.json"

git_info:
  info_path: "mxpack/git_info.json"

version_info:
  info_path: "mxpack/version_info.json"

conda_build_info:
  info_path: "mxpack/conda_build__pre_build__info.json"
  post_path: "mxpack/conda_build__post_build__info.json"
  publish_artifacts_path: "mxpack/conda_artifactory_publish_info.json"

mkdocs_info:
  info_path: "mxpack/mkdocs__pre_build__info.json"
  post_path: "mxpack/mkdocs__post_build__info.json"
