# @desc: "a conventional conda package recipe meta data [ meta.yaml ] enriched with extra meta data for dev-x boost"
# @desc: "sections that are added on top of conda meta.yaml are prefixed with `mx-`"

package:
  name: road-eval-dashboard
  version: "{{ environ.get('MX_PACKAGE_VERSION', '_NO_PACKAGE_VERSION_') }}"

source:
  path: ../.. # relative path to setup.cfg

build:
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed -vv ."
  noarch: python
  ignore_prefix_files:
    - __localbuild__

  entry_points:
    - "road-eval-dashboard_cli = road_eval_dashboard.dummy_main_module:main"

test:
  requires:
    - pytest
    - pytest-xdist
    - pytest-cov
    - pytest-html
    - coverage
    - loguru
  source_files:
    - tests/
    - tasks/
    - _infra/
    - version/
    - __build_info/
    - setup.cfg
    - Taskfile.yml

requirements:
  # ---/ conda spec sections

  # # @info: "for c/cpp build / cython require Anaconda compilers"
  # # @info: "see [Anaconda compilers](https://docs.conda.io/projects/conda-build/en/latest/resources/compiler-tools.html#anaconda-compiler-tools)"
  # build:
  #   - "{{ compiler('cxx') }}"
  #   - "{{ compiler('c') }}"
  #   - cython

  host:
    - python {{ python }}
    - pip
    - mxpcli >=0.24,<0.25

  run:
    - python
    - pydantic
    - fire
    - pyyaml
    - loguru
    - orjson
    - typing_extensions >=3.7.4
    - pycountry
    - dash-bootstrap-components
    - dash-daq
    - numpy
    - pandas
    - boto3
    - tqdm
    - s3fs
    - fsspec
    - road-database-toolkit

  mx_build_deps:
    - boa
    - conda-build =3.28.4
    - python
    - conda-pack
    - conda-lock
    - build
    - twine
    - typing_extensions >=3.7.4
    - pyyaml
    - semver
    - orjson
    - mxpcli >=0.24,<0.25
    - requests
    - black

  mx_test_deps:
    - python
    - pytest
    - pytest-xdist
    - pytest-cov
    - pytest-html
    - coverage
    - yapf
    - semver
    - pydantic
    - loguru
    - mxpcli >=0.24,<0.25

  mx_dev_only_deps:
    - jupyter
    - jupyterlab
    - ipython
    - plotly
    - pyyaml
    - orjson
    - rope
    - mxpcli >=0.24,<0.25

about:
  author: "Nadav Shemesh"
  home: http://gitlab.mobileye.com/road_algo/road_eval_dashboard
  home_dir: road_eval_dashboard
  summary: "TODO: write a summary of your package"
  license: "Mobileye, LTD"
  author_email: "nadav.shemesh@mobileye.com"
  author_emails:
    - "nadav.shemesh@mobileye.com"
    - "dor.eagelberg@mobileye.com"
    - "yair.shemer@mobileye.com"
